# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

name: mq-metric-samples

replicaCount: 1

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 9157

service:
  type: ClusterIP
  port: 9157

route:
  enabled: true

ingress:
  enabled: false

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: SECUREQM

configmap:
  QM: "SECUREQM"
  CONNECTION_NAME: "secureqm-ibm-mq-qm-mq.itzroks-6620022xah-xygpqn-4b4a324f027aea19c5cbc0c3275c4656-0000.us-south.containers.appdomain.cloud"
  CHANNEL: "SECUREQMCHL"
  QUEUES: "!SYSTEM.*,!AMQ.*,*"
  SUBSCRIPTIONS: "!$SYS*"
  TOPICS: "!*"
  USE_PUBLICATIONS: false
  USE_OBJECT_STATUS: true
  CONFIGURATION_FILE: ""
  LOG_LEVEL: "INFO"
